spring:
  config:
    activate:
      on-profile: local

vote-assembly:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/vote_assembly?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123
    maximumPoolSize: 3
    minimumPoolSize: 3
    connectionTestQuery: SELECT 1
    poolName: staging-vote-assembly-pool
    driverClassName: com.mysql.cj.jdbc.Driver
