server:
  port: 8080
  compression:
    enabled: true
    mime-types:
      - application/json

spring:
  application:
    name: vote-assembly
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:/db/changelog.xml
sql:
  base-path:
    associate: 'associate'
    session: 'session'
    subject: 'subject'
    vote: 'vote'
aws:
  s3:
    session: "vote-assembly"
  access-key:
  secret-key:
  sns:
    topic:
      session-vote: "arn:aws:sns:us-east-1:381492217956:topic_backoffice_session_vote"







