server:
  port: 8080
  compression:
    enabled: true
    mime-types:
      - application/json

springdoc:
  show-actuator: true
  packagesToScan: com.backoffice.app.application.api

spring:
  application:
    name: api-vote-assembly
  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: false
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


sql:
  base-path:
    associate: 'associate/'
    session: 'session/'
    subject: 'subject/'
    vote: 'vote/'
aws:
  s3:
    session: "vote-assembly"
  access-key:
  secret-key:
  sns:
    topic:
      session-vote: "arn:aws:sns:us-east-1:381492217956:topic_backoffice_session_vote"







