name: quality

on:
  workflow_call:
    pull_request:
      branches:
      - master

jobs:
  pipeline-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: run unit test
        run: mvn clean test

      - name: run integration test
        run: mvn clean integration-test



